export const FETCH_ACCOUNTS_REQUEST = 'FETCH_ACCOUNTS_REQUEST';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAILURE = 'FETCH_ACCOUNTS_FAILURE';

export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const CREATE_ACCOUNT_ADMIN_FAIL = 'CREATE_ACCOUNT_ADMIN_FAIL';
export const FETCH_ACCOUNT_DETAIL_REQUEST = 'FETCH_ACCOUNT_DETAIL_REQUEST';
export const SEACRH_ACCOUNT_USER_SUCCESS = 'SEACRH_ACCOUNT_USER_SUCCESS';
export const FETCH_ACCOUNT_DETAIL_SUCCESS = 'FETCH_ACCOUNT_DETAIL_SUCCESS';
export const FETCH_ACCOUNT_DETAIL_FAILURE = 'FETCH_ACCOUNT_DETAIL_FAILURE';

export const FETCH_ACCOUNT_DASHBOARD_LIST_REQUEST = 'FETCH_ACCOUNT_DASHBOARD_LIST_REQUEST';
export const FETCH_ACCOUNT_DASHBOARD_LIST_SUCCESS = 'FETCH_ACCOUNT_DASHBOARD_LIST_SUCCESS';
export const FETCH_ACCOUNT_DASHBOARD_LIST_FAIL = 'FETCH_ACCOUNT_DASHBOARD_LIST_FAIL';

export const UPDATE_ACCOUNT_DETAIL_REQUEST = 'UPDATE_ACCOUNT_DETAIL_REQUEST';
export const UPDATE_ACCOUNT_DETAIL_SUCCESS = 'UPDATE_ACCOUNT_DETAIL_SUCCESS';
export const UPDATE_ACCOUNT_DETAIL_FAIL = 'UPDATE_ACCOUNT_DETAIL_FAIL';

export const UPDATE_ACCOUNT_ADMIN_REQUEST = 'UPDATE_ACCOUNT_ADMIN_REQUEST';
export const UPDATE_ACCOUNT_ADMIN_SUCCESS = 'UPDATE_ACCOUNT_ADMIN_SUCCESS';
export const UPDATE_ACCOUNT_ADMIN_FAIL = 'UPDATE_ACCOUNT_ADMIN_FAIL';

export const CREATE_ACCOUNT_ADMIN_REQUEST = 'CREATE_ACCOUNT_ADMIN_REQUEST';
export const CREATE_ACCOUNT_ADMIN_SUCCESS = 'CREATE_ACCOUNT_ADMIN_SUCCESS';

export const DELETE_ACCOUNT_ADMIN_REQUEST = 'DELETE_ACCOUNT_ADMIN_REQUEST';
export const DELETE_ACCOUNT_ADMIN_SUCCESS = 'DELETE_ACCOUNT_ADMIN_SUCCESS';
export const DELETE_ACCOUNT_ADMIN_FAIL = 'DELETE_ACCOUNT_ADMIN_FAIL';

export const ACTIVATE_ACCOUNT_REQUEST = 'ACTIVATE_ACCOUNT_REQUEST';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAIL = 'ACTIVATE_ACCOUNT_FAIL';

export const REMOVE_DEACTIVATED_ACCOUNT_LIST = 'REMOVE_DEACTIVATED_ACCOUNT_LIST';

export const DEACTIVATE_ACCOUNT_REQUEST = 'DEACTIVATE_ACCOUNT_REQUEST';
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS';
export const DEACTIVATE_ACCOUNT_FAIL = 'DEACTIVATE_ACCOUNT_FAIL';

export const FETCH_ACCOUNT_OPTIONS_REQUEST = 'FETCH_ACCOUNT_OPTIONS_REQUEST';
export const FETCH_ACCOUNT_OPTIONS_SUCCESS = 'FETCH_ACCOUNT_OPTIONS_SUCCESS';
export const FETCH_ACCOUNT_OPTIONS_FAILURE = 'FETCH_ACCOUNT_OPTIONS_FAILURE';
export const FETCH_ACCOUNT_ADMIN_REQUEST = 'FETCH_ACCOUNT_ADMIN_REQUEST';
export const FETCH_ACCOUNT_ADMIN_SUCCESS = 'FETCH_ACCOUNT_ADMIN_SUCCESS';
export const FETCH_ACCOUNT_ADMIN_FAILURE = 'FETCH_ACCOUNT_ADMIN_FAILURE';

export const CLEAR_ACCOUNT_DETAILS = 'CLEAR_ACCOUNT_DETAILS';

export const SET_ACCOUNT_DETAILS = 'SET_ACCOUNT_DETAILS';

export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS';

export const CLEAR_ACCOUNT_ADMIN = 'CLEAR_ACCOUNT_ADMIN';

export const FETCH_CLINICAL_WORKFLOW_REQUEST = 'FETCH_CLINICAL_WORKFLOW_REQUEST';
export const FETCH_CLINICAL_WORKFLOW_SUCCESS = 'FETCH_CLINICAL_WORKFLOW_SUCCESS';
export const FETCH_CLINICAL_WORKFLOW_FAILURE = 'FETCH_CLINICAL_WORKFLOW_FAILURE';

export const CREATE_ACCOUNT_WORKFLOW_MODULE_REQUEST = 'CREATE_ACCOUNT_WORKFLOW_MODULE_REQUEST';
export const CREATE_ACCOUNT_WORKFLOW_MODULE_SUCCESS = 'CREATE_ACCOUNT_WORKFLOW_MODULE_SUCCESS';
export const CREATE_ACCOUNT_WORKFLOW_MODULE_FAILURE = 'CREATE_ACCOUNT_WORKFLOW_MODULE_FAILURE';

export const UPDATE_ACCOUNT_WORKFLOW_MODULE_REQUEST = 'UPDATE_ACCOUNT_WORKFLOW_MODULE_REQUEST';
export const UPDATE_ACCOUNT_WORKFLOW_MODULE_SUCCESS = 'UPDATE_ACCOUNT_WORKFLOW_MODULE_SUCCESS';
export const UPDATE_ACCOUNT_WORKFLOW_MODULE_FAILURE = 'UPDATE_ACCOUNT_WORKFLOW_MODULE_FAILURE';

export const DELETE_ACCOUNT_WORKFLOW_MODULE_REQUEST = 'DELETE_ACCOUNT_WORKFLOW_MODULE_REQUEST';
export const DELETE_ACCOUNT_WORKFLOW_MODULE_SUCCESS = 'DELETE_ACCOUNT_WORKFLOW_MODULE_SUCCESS';
export const DELETE_ACCOUNT_WORKFLOW_MODULE_FAILURE = 'DELETE_ACCOUNT_WORKFLOW_MODULE_FAILURE';

export const RESET_CLINICAL_WORKFLOW_REQUEST = 'RESET_CLINICAL_WORKFLOW_REQUEST';
