export const FETCH_SUPERADMINS_REQUEST = 'FETCH_SUPERADMINS_REQUEST';
export const FETCH_SUPERADMINS_SUCCESS = 'FETCH_SUPERADMINS_SUCCESS';
export const FETCH_SUPERADMINS_FAILURE = 'FETCH_SUPERADMINS_FAILURE';

export const CREATE_SUPER_ADMIN_REQUEST = 'CREATE_SUPER_ADMIN_REQUEST';
export const CREATE_SUPER_ADMIN_SUCCESS = 'CREATE_SUPER_ADMIN_SUCCESS';
export const CREATE_SUPER_ADMIN_FAILURE = 'CREATE_SUPER_ADMIN_FAILURE';

export const DELETE_SUPER_ADMIN_REQUEST = 'DELETE_SUPER_ADMIN_REQUEST';
export const DELETE_SUPER_ADMIN_SUCCESS = 'DELETE_SUPER_ADMIN_SUCCESS';
export const DELETE_SUPER_ADMIN_FAIL = 'DELETE_SUPER_ADMIN_FAIL';

export const UPDATE_SUPER_ADMIN_REQUEST = 'UPDATE_SUPER_ADMIN_REQUEST';
export const UPDATE_SUPER_ADMIN_SUCCESS = 'UPDATE_SUPER_ADMIN_SUCCESS';
export const UPDATE_SUPER_ADMIN_FAIL = 'UPDATE_SUPER_ADMIN_FAIL';

export const FETCH_SUPER_ADMIN_REQUEST = 'FETCH_SUPER_ADMIN_REQUEST';
export const FETCH_SUPER_ADMIN_SUCCESS = 'FETCH_SUPER_ADMIN_SUCCESS';
export const FETCH_SUPER_ADMIN_FAIL = 'FETCH_SUPER_ADMIN_FAIL';
