export const FETCH_LABTEST_REQUEST = 'FETCH_LABTEST_REQUEST';
export const FETCH_LABTEST_SUCCESS = 'FETCH_LABTEST_SUCCESS';
export const FETCH_LABTEST_FAILURE = 'FETCH_LABTEST_FAILURE';

export const FETCH_LABTEST_BY_ID_REQUEST = 'FETCH_LABTEST_BY_ID_REQUEST';
export const FETCH_LABTEST_BY_ID_SUCCESS = 'FETCH_LABTEST_BY_ID_SUCCESS';
export const FETCH_LABTEST_BY_ID_FAILURE = 'FETCH_LABTEST_BY_ID_FAILURE';

export const CREATE_LABTEST_REQUEST = 'CREATE_LABTEST_REQUEST';
export const CREATE_LABTEST_SUCCESS = 'CREATE_LABTEST_SUCCESS';
export const CREATE_LABTEST_FAILURE = 'CREATE_LABTEST_FAILURE';

export const UPDATE_LABTEST_REQUEST = 'UPDATE_LABTEST_REQUEST';
export const UPDATE_LABTEST_SUCCESS = 'UPDATE_LABTEST_SUCCESS';
export const UPDATE_LABTEST_FAILURE = 'UPDATE_LABTEST_FAILURE';

export const DELETE_LABTEST_REQUEST = 'DELETE_LABTEST_REQUEST';
export const DELETE_LABTEST_SUCCESS = 'DELETE_LABTEST_SUCCESS';
export const DELETE_LABTEST_FAILURE = 'DELETE_LABTEST_FAILURE';

export const FETCH_UNIT_LIST_REQUEST = 'FETCH_UNIT_LIST_REQUEST';
export const FETCH_UNIT_LIST_SUCCESS = 'FETCH_UNIT_LIST_SUCCESS';
export const FETCH_UNIT_LIST_FAILURE = 'FETCH_UNIT_LIST_FAILURE';

export const CLEAR_UNIT_LIST_REQUEST = 'CLEAR_UNIT_LIST_REQUEST';

export const FETCH_LABTEST_RESULT_RANGE_LIST_REQUEST = 'FETCH_LABTEST_RESULT_RANGE_LIST_REQUEST';
export const FETCH_LABTEST_RESULT_RANGE_LIST_SUCCESS = 'FETCH_LABTEST_RESULT_RANGE_LIST_SUCCESS';
export const FETCH_LABTEST_RESULT_RANGE_LIST_FAILURE = 'FETCH_LABTEST_RESULT_RANGE_LIST_FAILURE';

export const SAVE_LABTEST_RESULT_RANGES_REQUEST = 'SAVE_LABTEST_RESULT_RANGES_REQUEST';
export const SAVE_LABTEST_RESULT_RANGES_SUCCESS = 'SAVE_LABTEST_RESULT_RANGES_SUCCESS';
export const SAVE_LABTEST_RESULT_RANGES_FAILURE = 'SAVE_LABTEST_RESULT_RANGES_FAILURE';

export const LABTEST_RESULT_RANGE_DELETE_REQUEST = 'LABTEST_RESULT_RANGE_DELETE_REQUEST';
export const LABTEST_RESULT_RANGE_DELETE_SUCCESS = 'LABTEST_RESULT_RANGE_DELETE_SUCCESS';
export const LABTEST_RESULT_RANGE_DELETE_FAILURE = 'LABTEST_RESULT_RANGE_DELETE_FAILURE';
