export const FETCH_CUSTOMIZATION_FORM_REQUEST = 'FETCH_CUSTOMIZATION_FORM_REQUEST';
export const FETCH_CUSTOMIZATION_FORM_SUCCESS = 'FETCH_CUSTOMIZATION_FORM_SUCCESS';
export const FETCH_CUSTOMIZATION_FORM_FAILURE = 'FETCH_CUSTOMIZATION_FORM_FAILURE';

export const FETCH_CONSENT_FORM_SUCCESS = 'FETCH_CONSENT_FORM_SUCCESS';
export const FETCH_CONSENT_FORM_FAILURE = 'FETCH_CONSENT_FORM_FAILURE';

export const CLEAR_CONSENT_FORM = 'CLEAR_CONSENT_FORM';

export const FETCH_FORM_META_REQUEST = 'FETCH_FORM_META_REQUEST';
export const FETCH_FORM_META_SUCCESS = 'FETCH_FORM_META_SUCCESS';
export const FETCH_FORM_META_FAILURE = 'FETCH_FORM_META_FAILURE';

export const CLEAR_FORM_JSON = 'CLEAR_FORM_JSON';
export const CLEAR_FORM_META = 'CLEAR_FORM_META';

export const CUSTOMIZE_FORM_REQUEST = 'CUSTOMIZE_FORM_REQUEST';
export const CUSTOMIZE_FORM_SUCCESS = 'CUSTOMIZE_FORM_SUCCESS';
export const CUSTOMIZE_FORM_FAILURE = 'CUSTOMIZE_FORM_FAILURE';

export const DEACTIVATE_CONSENT_FORM_REQUEST = 'DEACTIVATE_CONSENT_FORM_REQUEST';
export const DEACTIVATE_CONSENT_FORM_SUCCESS = 'DEACTIVATE_CONSENT_FORM_SUCCESS';
export const DEACTIVATE_CONSENT_FORM_FAILURE = 'DEACTIVATE_CONSENT_FORM_FAILURE';
