export const FETCH_PROGRAM_LIST_REQUEST = 'FETCH_PROGRAM_LIST_REQUEST';
export const FETCH_PROGRAM_LIST_SUCCESS = 'FETCH_PROGRAM_LIST_SUCCESS';
export const FETCH_PROGRAM_LIST_FAILURE = 'FETCH_PROGRAM_LIST_FAILURE';

export const DELETE_PROGRAM_REQUEST = 'DELETE_PROGRAM_REQUEST';
export const DELETE_PROGRAM_SUCCESS = 'DELETE_PROGRAM_SUCCESS';
export const DELETE_PROGRAM_FAILURE = 'DELETE_PROGRAM_FAILURE';

export const CLEAR_PROGRAM_LIST = 'CLEAR_PROGRAM_LIST';

export const FETCH_PROGRAM_DETAILS_REQUEST = 'FETCH_PROGRAM_DETAILS_REQUEST';
export const FETCH_PROGRAM_DETAILS_SUCCESS = 'FETCH_PROGRAM_DETAILS_SUCCESS';
export const FETCH_PROGRAM_DETAILS_FAILURE = 'FETCH_PROGRAM_DETAILS_FAILURE';

export const CREATE_PROGRAM_REQUEST = 'CREATE_PROGRAM_REQUEST';
export const CREATE_PROGRAM_REQUEST_SUCCESS = 'CREATE_PROGRAM_REQUEST_SUCCESS';
export const CREATE_PROGRAM_REQUEST_FAIL = 'CREATE_PROGRAM_REQUEST_FAIL';

export const UPDATE_PROGRAM_REQUEST = 'UPDATE_PROGRAM_REQUEST';
export const UPDATE_PROGRAM_SUCCESS = 'UPDATE_PROGRAM_SUCCESS';
export const UPDATE_PROGRAM_FAILURE = 'UPDATE_PROGRAM_FAILURE';
