export const FETCH_REGIONS_REQUEST = 'FETCH_REGIONS_REQUEST';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILURE = 'FETCH_REGIONS_FAILURE';

export const CREATE_REGION_REQUEST = 'CREATE_REGION_REQUEST';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_FAILURE = 'CREATE_REGION_FAILURE';

export const FETCH_REGION_DETAIL_REQUEST = 'FETCH_REGION_DETAIL_REQUEST';
export const FETCH_REGION_DETAIL_SUCCESS = 'FETCH_REGION_DETAIL_SUCCESS';
export const FETCH_REGION_DETAIL_FAILURE = 'FETCH_REGION_DETAIL_FAILURE';

export const SEACRH_REGION_USER_SUCCESS = 'SEACRH_REGION_USER_SUCCESS';

export const UPDATE_REGION_DETAIL_REQUEST = 'UPDATE_REGION_DETAIL_REQUEST';
export const UPDATE_REGION_DETAIL_SUCCESS = 'UPDATE_REGION_DETAIL_SUCCESS';
export const UPDATE_REGION_DETAIL_FAIL = 'UPDATE_REGION_DETAIL_FAIL';

export const UPDATE_REGION_ADMIN_REQUEST = 'UPDATE_REGION_ADMIN_REQUEST';
export const UPDATE_REGION_ADMIN_SUCCESS = 'UPDATE_REGION_ADMIN_SUCCESS';
export const UPDATE_REGION_ADMIN_FAIL = 'UPDATE_REGION_ADMIN_FAIL';

export const CREATE_REGION_ADMIN_REQUEST = 'CREATE_REGION_ADMIN_REQUEST';
export const CREATE_REGION_ADMIN_SUCCESS = 'CREATE_REGION_ADMIN_SUCCESS';
export const CREATE_REGION_ADMIN_FAIL = 'CREATE_REGION_ADMIN_FAIL';

export const DELETE_REGION_ADMIN_REQUEST = 'DELETE_REGION_ADMIN_REQUEST';
export const DELETE_REGION_ADMIN_SUCCESS = 'DELETE_REGION_ADMIN_SUCCESS';
export const DELETE_REGION_ADMIN_FAIL = 'DELETE_REGION_ADMIN_FAIL';

export const DEACTIVATE_REGION_REQUEST = 'DEACTIVATE_REGION_REQUEST';
export const DEACTIVATE_REGION_SUCCESS = 'DEACTIVATE_REGION_SUCCESS';
export const DEACTIVATE_REGION_FAIL = 'DEACTIVATE_REGION_FAIL';

export const SET_REGION_DETAILS = 'SET_REGION_DETAILS';

export const CLEAR_REGION_DETAIL = 'CLEAR_REGION_DETAIL';
