export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const GET_USERNAME_FOR_PASSWORD_RESET = 'GET_USERNAME_FOR_PASSWORD_RESET';
export const GET_USERNAME_FOR_PASSWORD_RESET_SUCCESS = 'GET_USERNAME_FOR_PASSWORD_RESET_SUCCESS';
export const GET_USERNAME_FOR_PASSWORD_RESET_FAIL = 'GET_USERNAME_FOR_PASSWORD_RESET_FAIL';

export const CREATE_PASSWORD_REQUEST = 'CREATE_PASSWORD_REQUEST';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAIL = 'CREATE_PASSWORD_FAIL';

export const FETCH_TIMEZONE_LIST_REQUEST = 'FETCH_TIMEZONE_LIST_REQUEST';
export const FETCH_TIMEZONE_LIST_SUCCESS = 'FETCH_TIMEZONE_LIST_SUCCESS';
export const FETCH_TIMEZONE_LIST_FAILURE = 'FETCH_TIMEZONE_LIST_FAILURE';

export const FETCH_CULTURE_LIST_REQUEST = 'FETCH_CULTURE_LIST_REQUEST';
export const FETCH_CULTURE_LIST_SUCCESS = 'FETCH_CULTURE_LIST_SUCCESS';
export const FETCH_CULTURE_LIST_FAILURE = 'FETCH_CULTURE_LIST_FAILURE';

export const FETCH_LOGGED_IN_USER_REQUEST = 'FETCH_LOGGED_IN_USER_REQUEST';
export const FETCH_LOGGED_IN_USER_SUCCESS = 'FETCH_LOGGED_IN_USER_SUCCESS';
export const FETCH_LOGGED_IN_USER_FAILURE = 'FETCH_LOGGED_IN_USER_FAILURE';

export const SESSION_TIMEDOUT = 'SESSION_TIMEDOUT';
export const RESET_STORE = 'RESET_STORE';

export const FETCH_USER_BY_EMAIL = 'FETCH_USER_BY_EMAIL';
export const FETCH_USER_BY_EMAIL_SUCCESS = 'FETCH_USER_BY_EMAIL_SUCCESS';
export const FETCH_USER_BY_EMAIL_FAIL = 'FETCH_USER_BY_EMAIL_FAIL';

export const FETCH_USER_BY_ID_REQUEST = 'FETCH_USER_BY_ID_REQUEST';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAILURE = 'FETCH_USER_BY_ID_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FETCH_COUNTRY_LIST_REQUEST = 'FETCH_COUNTRY_LIST_REQUEST';
export const FETCH_COUNTRY_LIST_SUCCESS = 'FETCH_COUNTRY_LIST_SUCCESS';
export const FETCH_COUNTRY_LIST_FAILURE = 'FETCH_COUNTRY_LIST_FAILURE';

export const AUTH_TOKEN = 'AUTH_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const ADD_USER_TENANT_ID = 'ADD_USER_TENANT_ID';
export const REMOVE_USER_TENANT_ID = 'REMOVE_USER_TENANT_ID';
export const FETCH_LOCKED_USERS_REQUEST = 'FETCH_LOCKED_USERS_REQUEST';
export const FETCH_LOCKED_USERS_SUCCESS = 'FETCH_LOCKED_USERS_SUCCESS';
export const FETCH_LOCKED_USERS_FAILURE = 'FETCH_LOCKED_USERS_FAILURE';

export const UNLOCK_USERS_REQUEST = 'UNLOCK_USERS_REQUEST';
export const UNLOCK_USERS_SUCCESS = 'UNLOCK_USERS_SUCCESS';
export const UNLOCK_USERS_FAILURE = 'UNLOCK_USERS_FAILURE';
