export const FETCH_MEDICATIONS_LIST_REQUEST = 'FETCH_MEDICATIONS_REQUEST';
export const FETCH_MEDICATIONS_LIST_SUCCESS = 'FETCH_MEDICATIONS_SUCCESS';
export const FETCH_MEDICATIONS_LIST_FAILURE = 'FETCH_MEDICATIONS_FAILURE';

export const FETCH_MEDICATION_CLASSIFICATIONS_REQUEST = 'FETCH_MEDICATION_CLASSIFICATIONS_REQUEST';
export const FETCH_MEDICATION_CLASSIFICATIONS_SUCCESS = 'FETCH_MEDICATION_CLASSIFICATIONS_SUCCESS';
export const FETCH_MEDICATION_CLASSIFICATIONS_FAILURE = 'FETCH_MEDICATION_CLASSIFICATIONS_FAILURE';

export const FETCH_MEDICATION_BRANDS = 'FETCH_MEDICATION_BRANDS';
export const FETCH_MEDICATION_BRANDS_SUCCESS = 'FETCH_MEDICATION_BRANDS_SUCCESS';
export const FETCH_MEDICATION_BRANDS_FAILURE = 'FETCH_MEDICATION_BRANDS_FAILURE';
export const REMOVE_MEDICATION_BRANDS = 'REMOVE_MEDICATION_BRANDS';

export const FETCH_MEDICATION_DOSAGE_FORM = 'FETCH_MEDICATION_DOSAGE_FORM';
export const FETCH_MEDICATION_DOSAGE_FORM_SUCCESS = 'FETCH_MEDICATION_DOSAGE_FORM_SUCCESS';
export const FETCH_MEDICATION_DOSAGE_FORM_FAILURE = 'FETCH_MEDICATION_DOSAGE_FORM_FAILURE';

export const CREATE_MEDICATION_REQUEST = 'CREATE_MEDICATION_REQUEST';
export const CREATE_MEDICATION_SUCCESS = 'CREATE_MEDICATION_SUCCESS';
export const CREATE_MEDICATION_FAILURE = 'CREATE_MEDICATION_FAILURE';

export const UPDATE_MEDICATION_REQUEST = 'UPDATE_MEDICATION_REQUEST';
export const UPDATE_MEDICATION_SUCCESS = 'UPDATE_MEDICATION_SUCCESS';
export const UPDATE_MEDICATION_FAILURE = 'UPDATE_MEDICATION_FAILURE';

export const DELETE_MEDICATION_REQUEST = 'DELETE_MEDICATION_REQUEST';
export const DELETE_MEDICATION_SUCCESS = 'DELETE_MEDICATION_SUCCESS';
export const DELETE_MEDICATION_FAILURE = 'DELETE_MEDICATION_FAILURE';

export const VALIDATE_MEDICATION = 'VALIDATE_MEDICATION';
