export const FETCH_OPERATING_UNIT_DASHBOARD_LIST_REQUEST = 'FETCH_OPERATING_UNIT_DASHBOARD_LIST_REQUEST';
export const FETCH_OPERATING_UNIT_DASHBOARD_LIST_SUCCESS = 'FETCH_OPERATING_UNIT_DASHBOARD_LIST_SUCCESS';
export const FETCH_OPERATING_UNIT_DASHBOARD_LIST_FAILURE = 'FETCH_OPERATING_UNIT_DASHBOARD_LIST_FAILURE';

export const FETCH_OPERATING_UNIT_DETAIL_REQUEST = 'FETCH_OPERATING_UNIT_DETAIL_REQUEST';
export const FETCH_OPERATING_UNIT_DETAIL_SUCCESS = 'FETCH_OPERATING_UNIT_DETAIL_SUCCESS';
export const FETCH_OPERATING_UNIT_DETAIL_FAILURE = 'FETCH_OPERATING_UNIT_DETAIL_FAILURE';

export const SEARCH_OPERATING_UNIT_USER_SUCCESS = 'SEARCH_OPERATING_UNIT_USER_SUCCESS';

export const FETCH_OPERATING_UNIT_LIST_REQUEST = 'FETCH_OPERATING_UNIT_LIST_REQUEST';
export const FETCH_OPERATING_UNIT_LIST_SUCCESS = 'FETCH_OPERATING_UNIT_LIST_SUCCESS';
export const FETCH_OPERATING_UNIT_LIST_FAILURE = 'FETCH_OPERATING_UNIT_LIST_FAILURE';

export const CREATE_OPERATING_UNIT_REQUEST = 'CREATE_OPERATING_UNIT_REQUEST';
export const CREATE_OPERATING_UNIT_SUCCESS = 'CREATE_OPERATING_UNIT_SUCCESS';
export const CREATE_OPERATING_UNIT_FAILURE = 'CREATE_OPERATING_UNIT_FAILURE';

export const UPDATE_OPERATING_UNIT_REQUEST = 'UPDATE_OPERATING_UNIT_REQUEST';
export const UPDATE_OPERATING_UNIT_SUCCESS = 'UPDATE_OPERATING_UNIT_SUCCESS';
export const UPDATE_OPERATING_UNIT_FAILURE = 'UPDATE_OPERATING_UNIT_FAILURE';

export const UPDATE_OPERATING_UNIT_ADMIN_REQUEST = 'UPDATE_OPERATING_UNIT_ADMIN_REQUEST';
export const UPDATE_OPERATING_UNIT_ADMIN_SUCCESS = 'UPDATE_OPERATING_UNIT_ADMIN_SUCCESS';
export const UPDATE_OPERATING_UNIT_ADMIN_FAILURE = 'UPDATE_OPERATING_UNIT_ADMIN_FAILURE';

export const CREATE_OPERATING_UNIT_ADMIN_REQUEST = 'CREATE_OPERATING_UNIT_ADMIN_REQUEST';
export const CREATE_OPERATING_UNIT_ADMIN_SUCCESS = 'CREATE_OPERATING_UNIT_ADMIN_SUCCESS';
export const CREATE_OPERATING_UNIT_ADMIN_FAILURE = 'CREATE_OPERATING_UNIT_ADMIN_FAILURE';

export const DELETE_OPERATING_UNIT_ADMIN_REQUEST = 'DELETE_OPERATING_UNIT_ADMIN_REQUEST';
export const DELETE_OPERATING_UNIT_ADMIN_SUCCESS = 'DELETE_OPERATING_UNIT_ADMIN_SUCCESS';
export const DELETE_OPERATING_UNIT_ADMIN_FAILURE = 'DELETE_OPERATING_UNIT_ADMIN_FAILURE';

export const FETCH_OPERATING_UNIT_BY_ID_REQUEST = 'FETCH_OPERATING_UNIT_BY_ID_REQUEST';
export const FETCH_OPERATING_UNIT_BY_ID_SUCCESS = 'FETCH_OPERATING_UNIT_BY_ID_SUCCESS';
export const FETCH_OPERATING_UNIT_BY_ID_FAILURE = 'FETCH_OPERATING_UNIT_BY_ID_FAILURE';

export const FETCH_OPERATING_UNIT_ADMIN_BY_ID_REQUEST = 'FETCH_OPERATING_UNIT_ADMIN_BY_ID_REQUEST';
export const FETCH_OPERATING_UNIT_ADMIN_BY_ID_SUCCESS = 'FETCH_OPERATING_UNIT_ADMIN_BY_ID_SUCCESS';
export const FETCH_OPERATING_UNIT_ADMIN_BY_ID_FAILURE = 'FETCH_OPERATING_UNIT_ADMIN_BY_ID_FAILURE';

export const FETCH_OPERATING_UNIT_ADMIN_LIST_REQUEST = 'FETCH_OPERATING_UNIT_ADMIN_LIST_REQUEST';
export const FETCH_OPERATING_UNIT_ADMIN_LIST_SUCCESS = 'FETCH_OPERATING_UNIT_ADMIN_LIST_SUCCESS';
export const FETCH_OPERATING_UNIT_ADMIN_LIST_FAILURE = 'FETCH_OPERATING_UNIT_ADMIN_LIST_FAILURE';

export const CLEAR_OPERATING_UNIT_DETAIL = 'CLEAR_OPERATING_UNIT_DETAIL';

export const SET_OPERATING_UNIT_DETAILS = 'SET_OPERATING_UNIT_DETAILS';

export const CLEAR_OPERATING_UNIT_LIST = 'CLEAR_OPERATING_UNIT_LIST';

export const CLEAR_OPERATING_UNIT_ADMIN_LIST = 'CLEAR_OPERATING_UNIT_ADMIN_LIST';

export const FETCH_OPERATING_UNIT_DROPDOWN_REQUEST = 'FETCH_OPERATING_UNIT_DROPDOWN_REQUEST';
export const FETCH_OPERATING_UNIT_DROPDOWN_SUCCESS = 'FETCH_OPERATING_UNIT_DROPDOWN_SUCCESS';
export const FETCH_OPERATING_UNIT_DROPDOWN_FAIL = 'FETCH_OPERATING_UNIT_DROPDOWN_FAIL';

export const CLEAR_DROPDOWN_VALUES = 'CLEAR_DROPDOWN_VALUES';
