export const FETCH_SITE_LIST_REQUEST = 'FETCH_SITE_LIST_REQUEST';
export const FETCH_SITE_LIST_SUCCESS = 'FETCH_SITE_LIST_SUCCESS';
export const FETCH_SITE_LIST_FAILURE = 'FETCH_SITE_LIST_FAILURE';

export const CREATE_SITE_REQUEST = 'CREAT_SITE_REQUEST';
export const CREATE_SITE_SUCCESS = 'CREAT_SITE_SUCCESS';
export const CREATE_SITE_FAILURE = 'CREAT_SITE_FAILURE';

export const FETCH_COUNTY_DROPDOWN_REQUEST = 'FETCH_COUNTY_DROPDOWN_REQUEST';
export const FETCH_COUNTY_DROPDOWN_SUCCESS = 'FETCH_COUNTY_DROPDOWN_SUCCESS';
export const FETCH_COUNTY_DROPDOWN_FAILURE = 'FETCH_COUNTY_DROPDOWN_FAILURE';

export const FETCH_SUB_COUNTY_DROPDOWN_REQUEST = 'FETCH_SUB_COUNTY_DROPDOWN_REQUEST';
export const FETCH_SUB_COUNTY_DROPDOWN_SUCCESS = 'FETCH_SUB_COUNTY_DROPDOWN_SUCCESS';
export const FETCH_SUB_COUNTY_DROPDOWN_FAILURE = 'FETCH_SUB_COUNTY_DROPDOWN_FAILURE';

export const FETCH_CULTURE_DROPDOWN_REQUEST = 'FETCH_CULTURE_DROPDOWN_REQUEST';
export const FETCH_CULTURE_DROPDOWN_SUCCESS = 'FETCH_CULTURE_DROPDOWN_SUCCESS';
export const FETCH_CULTURE_DROPDOWN_FAILURE = 'FETCH_CULTURE_DROPDOWN_FAILURE';

export const CLEAR_DROPDOWN_VALUES = 'CLEAR_DROPDOWN_VALUES';

export const UPDATE_SITE_DETAILS_REQUEST = 'UPDATE_SITE_DETAILS_REQUEST';
export const UPDATE_SITE_DETAILS_SUCCESS = 'UPDATE_SITE_DETAILS_SUCCESS';
export const UPDATE_SITE_DETAILS_FAILURE = 'UPDATE_SITE_DETAILS_FAILURE';

export const FETCH_SITE_USER_LIST_REQUEST = 'FETCH_SITE_USER_LIST_REQUEST';
export const FETCH_SITE_USER_LIST_SUCCESS = 'FETCH_SITE_USER_LIST_SUCCESS';
export const FETCH_SITE_USER_LIST_FAILURE = 'FETCH_SITE_USER_LIST_FAILURE';

export const DELETE_SITE_USER_REQUEST = 'DELETE_SITE_USER_REQUEST';
export const DELETE_SITE_USER_SUCCESS = 'DELETE_SITE_USER_SUCCESS';
export const DELETE_SITE_USER_FAILURE = 'DELETE_SITE_USER_FAILURE';

export const CREATE_SITE_USER_REQUEST = 'CREATE_SITE_USER_REQUEST';
export const CREATE_SITE_USER_SUCCESS = 'CREATE_SITE_USER_SUCCESS';
export const CREATE_SITE_USER_FAILURE = 'CREATE_SITE_USER_FAILURE';

export const UPDATE_SITE_USER_REQUEST = 'UPDATE_SITE_USER_REQUEST';
export const UPDATE_SITE_USER_SUCCESS = 'UPDATE_SITE_USER_SUCCESS';
export const UPDATE_SITE_USER_FAILURE = 'UPDATE_SITE_USER_FAILURE';

export const FETCH_SITE_SUMMARY_REQUEST = 'FETCH_SITE_SUMMARY_REQUEST';
export const FETCH_SITE_SUMMARY_SUCCESS = 'FETCH_SITE_SUMMARY_SUCCESS';
export const FETCH_SITE_SUMMARY_FAILURE = 'FETCH_SITE_SUMMARY_FAILURE';

export const FETCH_SITE_USERS_REQUEST = 'FETCH_SITE_USERS_REQUEST';
export const FETCH_SITE_USERS_SUCCESS = 'FETCH_SITE_USERS_SUCCESS';
export const FETCH_SITE_USERS_FAILURE = 'FETCH_SITE_USERS_FAILURE';

export const FETCH_SITE_DASHBOARD_LIST_REQUEST = 'FETCH_SITE_DASHBOARD_LIST_REQUEST';
export const FETCH_SITE_DASHBOARD_LIST_SUCCESS = 'FETCH_SITE_DASHBOARD_LIST_SUCCESS';
export const FETCH_SITE_DASHBOARD_LIST_FAILURE = 'FETCH_SITE_DASHBOARD_LIST_FAILURE';

export const CLEAR_SITE_LIST = 'CLEAR_SITE_LIST';

export const CLEAR_SITE_USER_LIST = 'CLEAR_SITE_USER_LIST';

export const CLEAR_SITE_SUMMARY = 'CLEAR_SITE_SUMMARY';

export const SET_SITE_SUMMARY = 'SET_SITE_SUMMARY';

export const FETCH_SITE_DROPDOWN_REQUEST = 'FETCH_SITE_DROPDOWN_REQUEST';
export const FETCH_SITE_DROPDOWN_SUCCESS = 'FETCH_SITE_DROPDOWN_SUCCESS';
export const FETCH_SITE_DROPDOWN_FAILURE = 'FETCH_SITE_DROPDOWN_FAILURE';

export const CLEAR_SITE_DROPDOWN_OPTIONS = 'CLEAR_SITE_DROPDOWN_OPTIONS';
